"""Generate frontend/words.js: the local guess-validation dictionary.

Roman Wordle used to validate guesses against api.dictionaryapi.dev. That API
proved unreliable (see README), so the word list is bundled instead and no
network call happens on the guess path at all.

Run this whenever you want to refresh the list or extend ASTRO_NAMES:

    python3 build_words.py

Source corpus is /usr/share/dict/words (the `web2` list shipped with macOS and
most BSDs). It deliberately contains no proper nouns, which matters for an
astronomy game, so ASTRO_NAMES below supplies those by hand.
"""

import os
import sys

MIN_LEN, MAX_LEN = 4, 6
SYSTEM_DICT = "/usr/share/dict/words"
_HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(_HERE, "frontend", "words.js")

# Proper nouns and mission jargon web2 omits. Entries outside 4-6 letters are
# filtered out automatically, so it's safe to add names of any length here.
ASTRO_NAMES = """
    mercury venus earth mars jupiter saturn uranus neptune pluto luna sol
    ceres vesta pallas juno eris sedna haumea makemake charon
    phobos deimos europa titan mimas rhea dione tethys triton iapetus
    ariel oberon titania umbriel miranda nereid proteus larissa
    orion lyra cygnus draco virgo libra aries taurus gemini cancer leo
    pisces aquila corvus crux hydra lupus norma octans pavo pyxis vela
    carina dorado fornax indus lepus mensa musca tucana volans auriga
    bootes cetus columba grus lynx apus ara caelum camelopardalis
    canis capricornus cassiopeia centaurus cepheus chamaeleon circinus
    corona crater cygnus delphinus equuleus eridanus gemini hercules
    horologium hydrus lacerta lupus microscopium monoceros ophiuchus
    perseus phoenix pictor puppis reticulum sagitta scorpius sculptor
    scutum serpens sextans telescopium triangulum ursa vulpecula
    vega rigel sirius altair deneb spica pollux castor antares capella
    arcturus procyon mizar alcor algol merope maia electra regulus
    polaris canopus betelgeuse bellatrix aldebaran fomalhaut achernar
    nasa esa eso webb hubble kepler tess roman rubin euclid planck sloan
    gemini chandra spitzer swift wise juno cassini voyager pioneer
    galileo neowise lsst alma keck sofia iras cobe wmap sdss ztf vera
    ligo nancy grace herschel spherex plato ariel athena lisa
    halley kuiper oort bode lowell tycho brahe newton bohr hoyle sagan
    shapley leavitt payne cannon messier curtis eddington chandrasekhar
    apollo artemis gaia soho ace stereo parker solo maven juice
    magellan viking spirit curiosity perseverance ingenuity
    andromeda triangulum magellanic sombrero pinwheel whirlpool
    milky way local group virgo coma fornax perseus norma
"""


def main() -> int:
    if not os.path.exists(SYSTEM_DICT):
        sys.stderr.write(
            "error: %s not found. This script expects the BSD/macOS `web2`\n"
            "word list. On Debian/Ubuntu: apt-get install wamerican\n" % SYSTEM_DICT
        )
        return 1

    words = set()

    with open(SYSTEM_DICT, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            w = line.strip()
            if w.isalpha() and w.islower() and MIN_LEN <= len(w) <= MAX_LEN:
                words.add(w.upper())

    base_count = len(words)

    names = {
        w.upper()
        for w in ASTRO_NAMES.split()
        if w.isalpha() and MIN_LEN <= len(w) <= MAX_LEN
    }
    words |= names

    # The daily-word bank must always validate, even if a word never made it
    # into web2 or the supplement above.
    try:
        import tomllib

        with open(os.path.join(_HERE, ".streamlit", "secrets.toml"), "rb") as fh:
            bank = tomllib.load(fh)["game"]["words"]
        bank_set = {
            w.upper() for w in bank if isinstance(w, str) and w.isalpha()
        }
        words |= bank_set
    except Exception as exc:  # secrets.toml is gitignored; not fatal locally
        sys.stderr.write("warning: could not merge word bank (%s)\n" % exc)
        bank_set = set()

    payload = " ".join(sorted(words))

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write("// Generated by build_words.py - do not edit by hand.\n")
        fh.write("// %d words, %d-%d letters, uppercase.\n" % (len(words), MIN_LEN, MAX_LEN))
        fh.write("window.ROMAN_WORDLE_WORDS = new Set(\n  \"")
        fh.write(payload)
        fh.write("\".split(\" \")\n);\n")

    print("web2 base      : %d" % base_count)
    print("astro names    : %d (+%d new)" % (len(names), len(words) - base_count))
    print("bank merged    : %d" % len(bank_set))
    print("total written  : %d -> %s" % (len(words), OUT_PATH))
    print("file size      : %.1f KB" % (os.path.getsize(OUT_PATH) / 1024.0))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
